stages:
#  - build
#  - test
#  - docker_build
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  DOCKER_IMAGE_PREFIX: "repository/docker-private/demo-project/quarkus-helloworld"
  CI_REGISTRY_IMAGE: "172.30.38.4:8083/repository/docker-private/demo-project/quarkus-helloworld"

# build:
#   stage: build
#   image: pratik1945/openjdk11-docker:3.0.0testing
#   script:
#     - mvn clean package -DskipTests -Dquarkus.container-image.build=true
#   artifacts:
#     paths:
#       - target/*.jar

# test:
#   stage: test
#   image: maven:3.8.4-openjdk-11-slim
#   script:
#     - mvn $MAVEN_CLI_OPTS test sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
#   tags:
#    - master



build:
  stage: build
  image:
    name: openjdk11-docker:3.0.0testing
    entrypoint: [""]
  variables:
    DOCKER_HOST: tcp://dind.gitlab-runner:2375
  services:
  - name: docker:19.03.14-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
  before_script:
    - echo $DOCKER_AUTH_CONFIG > /root/.docker/config.json
    - echo "Preparing to push Docker image..."
  script:
    - mvn clean package -DskipTests -Dquarkus.container-image.build=true
    - docker images
    - docker tag "$DOCKER_IMAGE_PREFIX" "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
  tags:
    - master
