apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-quarkus-app
  namespace: quarkus-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-quarkus-app
  template:
    metadata:
      labels:
        app: my-quarkus-app
    spec:
      containers:
        - name: my-quarkus-app
          image: 172.30.38.4:8083/repository/docker-private/demo-project/quarkus-helloworld:VERSION
          ports:
            - containerPort: 8080
